Algoritmo sin_titulo
	//DECLARAR VARIABLES
	DEFINIR B,NUM,I,RES COMO ENTERO
	ESCRIBIR "LA TABLA A MOSTRAR"
	LEER B
	ESCRIBIR "INGRESE HASTA QUE NUMERO DESEA VER LA TABLA"
	LEER NUM
	Para I=0 Hasta NUM Con Paso  1 Hacer
		RES=B*I
		ESCRIBIR B,"X",I,"=",RES
	Fin Para
FinAlgoritmo
